car<-read.csv(file.choose())
world=(car$World)
china=(car$China)
usa=(car$United.States)
japan=(car$Japan)
germany=(car$Germany)
southKorea=(car$South.Korea)
india=(car$India)
mexico=(car$Mexico)
spain=(car$Spain)
brazil=(car$Brazil)
russia=(car$Russia)
thailand=(car$Thailand)
canada=(car$Canada)
france=(car$France)
turkey=(car$Turkey)
solvakia=(car$Slovakia)
czech=(car$Czech.Republic)
uk=(car$United.Kingdom)
iran=(car$Iran)
Italy=(car$Italy)
indonesia=(car$Indonesia)
southAfrica=(car$South.Africa)
malaysia=(car$Malaysia)
poland=(car$Poland)
romania=(car$Romania)
hungry=(car$Hungary)
moroco=(car$Morocco)
portugal=(car$Portugal)
argentina=(car$Argentina)
belgium=(car$Belgium)
sweden=(car$Sweden)
uzbekistan=(car$Uzbekistan)
taiwan=(car$Taiwan)
vietnam=(car$Vietnam)
slovenia=(car$Slovenia)
pak=(car$Pakistan)
austria=(car$Austria)
netherlands=(car$Netherlands)
finland=(car$Finland)
algeria=(car$Algeria)
colombia=(car$Colombia)
kazakhstan=(car$Kazakhstan)
serbia=(car$Serbia)
belarus=(car$Belarus)
egypt=(car$Egypt)
phillipines=(car$Philippines)
ukraine=(car$Ukraine)
australia=(car$Australia)
azerbaijan=(car$Azerbaijan)
ecuador=(car$Ecuador)
tunisia=(car$Tunisia)
year=(car$Year)




summary(car)
sd(vietnam,na.rm=TRUE)
sd(usa,na.rm = TRUE)
sd(algeria,na.rm=TRUE)
sd(argentina,na.rm=TRUE)
sd(australia,na.rm=TRUE)
sd(austria,na.rm=TRUE)
sd(azerbaijan,na.rm=TRUE)
sd(belarus,na.rm=TRUE)
sd(belgium,na.rm=TRUE)
sd(brazil,na.rm=TRUE)
sd(canada,na.rm=TRUE)
sd(china,na.rm=TRUE)
sd(colombia,na.rm=TRUE)
sd(czech,na.rm=TRUE)
sd(ecuador,na.rm=TRUE)
sd(egypt,na.rm=TRUE)
sd(finland,na.rm=TRUE)
sd(france,na.rm=TRUE)
sd(germany,na.rm=TRUE)
sd(hungry,na.rm=TRUE)
sd(india,na.rm=TRUE)
sd(indonesia,na.rm=TRUE)
sd(iran,na.rm=TRUE)
sd(Italy,na.rm=TRUE)
sd(japan,na.rm=TRUE)
sd(kazakhstan,na.rm=TRUE)
sd(malaysia,na.rm=TRUE)
sd(mexico,na.rm=TRUE)
sd(moroco,na.rm=TRUE)
sd(netherlands,na.rm=TRUE)
sd(pak,na.rm=TRUE)
sd(phillipines,na.rm=TRUE)
sd(poland,na.rm=TRUE)
sd(portugal,na.rm=TRUE)
sd(romania,na.rm=TRUE)
sd(russia,na.rm=TRUE)
sd(serbia,na.rm=TRUE)
sd(slovenia,na.rm=TRUE)
sd(solvakia,na.rm=TRUE)
sd(southAfrica,na.rm=TRUE)
sd(southKorea,na.rm=TRUE)
sd(spain,na.rm=TRUE)
sd(sweden,na.rm=TRUE)
sd(taiwan,na.rm=TRUE)
sd(thailand,na.rm=TRUE)
sd(tunisia,na.rm=TRUE)
sd(turkey,na.rm=TRUE)
sd(uk,na.rm=TRUE)
sd(ukraine,na.rm=TRUE)
sd(uzbekistan,na.rm=TRUE)
sd(world,na.rm=TRUE)


range(vietnam,na.rm = TRUE)
range(usa,na.rm = TRUE)
range(algeria,na.rm=TRUE)
range(argentina,na.rm=TRUE)
range(australia,na.rm=TRUE)
range(austria,na.rm=TRUE)
range(azerbaijan,na.rm=TRUE)
range(belarus,na.rm=TRUE)
range(belgium,na.rm=TRUE)
range(brazil,na.rm=TRUE)
range(canada,na.rm=TRUE)
range(china,na.rm=TRUE)
range(colombia,na.rm=TRUE)
range(czech,na.rm=TRUE)
range(ecuador,na.rm=TRUE)
range(egypt,na.rm=TRUE)
range(finland,na.rm=TRUE)
range(france,na.rm=TRUE)
range(germany,na.rm=TRUE)
range(hungry,na.rm=TRUE)
range(india,na.rm=TRUE)
range(indonesia,na.rm=TRUE)
range(iran,na.rm=TRUE)
range(Italy,na.rm=TRUE)
range(japan,na.rm=TRUE)
range(kazakhstan,na.rm=TRUE)
range(malaysia,na.rm=TRUE)
range(mexico,na.rm=TRUE)
range(moroco,na.rm=TRUE)
range(netherlands,na.rm=TRUE)
range(pak,na.rm=TRUE)
range(phillipines,na.rm=TRUE)
range(poland,na.rm=TRUE)
range(portugal,na.rm=TRUE)
range(romania,na.rm=TRUE)
range(russia,na.rm=TRUE)
range(serbia,na.rm=TRUE)
range(slovenia,na.rm=TRUE)
range(solvakia,na.rm=TRUE)
range(southAfrica,na.rm=TRUE)
range(southKorea,na.rm=TRUE)
range(spain,na.rm=TRUE)
range(sweden,na.rm=TRUE)
range(taiwan,na.rm=TRUE)
range(thailand,na.rm=TRUE)
range(tunisia,na.rm=TRUE)
range(turkey,na.rm=TRUE)
range(uk,na.rm=TRUE)
range(ukraine,na.rm=TRUE)
range(uzbekistan,na.rm=TRUE)
range(world,na.rm=TRUE)


plot(year,algeria,main = "Car Production In algeria",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,argentina,main = "Car Production In argentina",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,australia,main = "Car Production In australia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,austria,main = "Car Production In austria",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,azerbaijan,main = "Car Production In Azerbaijan",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,belarus,main = "Car Production In belarus",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,belgium,main = "Car Production In belgium",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,brazil,main = "Car Production In brazil",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,canada,main = "Car Production In canada",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,china,main = "Car Production In China",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,colombia,main = "Car Production In Colombia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,czech,main = "Car Production In Czech Republic",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,ecuador,main = "Car Production In Ecuador",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,egypt,main = "Car Production In Egypt",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,finland,main = "Car Production In Finland",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,france,main = "Car Production In France",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,germany,main = "Car Production In Germany",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,hungry,main = "Car Production In Hungry",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,india,main = "Car Production In India",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,indonesia,main = "Car Production In Indonesia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,iran,main = "Car Production In Iran",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,Italy,main = "Car Production In Italy",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,japan,main = "Car Production In Japan",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,kazakhstan,main = "Car Production In Kazakhatan",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,malaysia,main = "Car Production In Malaysia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,mexico,main = "Car Production In Mexico",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,moroco,main = "Car Production In Moroco",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,netherlands,main = "Car Production In Netherlands",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,pak,main = "Car Production In Pakistan",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,phillipines,main = "Car Production In Phillipines",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,poland,main = "Car Production In Poland",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,portugal,main = "Car Production In Portugal",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,romania,main = "Car Production In Romania",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,russia,main = "Car Production In Russia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,serbia,main = "Car Production In Serbia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,slovenia,main = "Car Production In Slovenia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,solvakia,main = "Car Production In Slovakia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,southAfrica,main = "Car Production In South Africa",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,southKorea,main = "Car Production In South Korea",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,spain,main = "Car Production In Spain",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,sweden,main = "Car Production In Sweden",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,taiwan,main = "Car Production In Taiwan",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,thailand,main = "Car Production In Thailand",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,tunisia,main = "Car Production In Tunisia",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,turkey,main = "Car Production In Turkey",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,uk,main = "Car Production In United Kingdom",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,ukraine,main = "Car Production In Ukraine",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,uzbekistan,main = "Car Production In Uzbekistan",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,world,main = "Car Production In World",type="o",xlab = "Time In Years",ylab = "Car Production",pch=19)
plot(year,usa,xlab="Time IN Years",ylab = "Production in Units",main = "Car Production In Usa",type = "l",pch=4)
plot(year,vietnam,xlab="Time IN Years",ylab = "Production in Units",main = "Car Production In Vietnam",type = "l",pch=4)


cor(year,vietnam,use = "complete.obs")
cor(year,usa,use = "complete.obs")
cor(year,algeria,use = "complete.obs")
cor(year,argentina,use = "complete.obs")
cor(year,australia,use = "complete.obs")
cor(year,austria,use = "complete.obs")
cor(year,azerbaijan,use = "complete.obs")
cor(year,belarus,use = "complete.obs")
cor(year,belgium,use = "complete.obs")
cor(year,brazil,use = "complete.obs")
cor(year,canada,use = "complete.obs")
cor(year,china,use = "complete.obs")
cor(year,colombia,use = "complete.obs")
cor(year,czech,use = "complete.obs")
cor(year,ecuador,use = "complete.obs")
cor(year,egypt,use = "complete.obs")
cor(year,finland,use = "complete.obs")
cor(year,france,use = "complete.obs")
cor(year,germany,use = "complete.obs")
cor(year,hungry,use = "complete.obs")
cor(year,india,use = "complete.obs")
cor(year,indonesia,use = "complete.obs")
cor(year,iran,use = "complete.obs")
cor(year,Italy,use = "complete.obs")
cor(year,japan,use = "complete.obs")
cor(year,kazakhstan,use = "complete.obs")
cor(year,malaysia,use = "complete.obs")
cor(year,mexico,use = "complete.obs")
cor(year,moroco,use = "complete.obs")
cor(year,netherlands,use = "complete.obs")
cor(year,pak,use = "complete.obs")
cor(year,phillipines,use = "complete.obs")
cor(year,poland,use = "complete.obs")
cor(year,portugal,use = "complete.obs")
cor(year,romania,use = "complete.obs")
cor(year,russia,use = "complete.obs")
cor(year,serbia,use = "complete.obs")
cor(year,slovenia,use = "complete.obs")
cor(year,solvakia,use = "complete.obs")
cor(year,southAfrica,use = "complete.obs")
cor(year,southKorea,use = "complete.obs")
cor(year,spain,use = "complete.obs")
cor(year,sweden,use = "complete.obs")
cor(year,taiwan,use = "complete.obs")
cor(year,thailand,use = "complete.obs")
cor(year,tunisia,use = "complete.obs")
cor(year,turkey,use = "complete.obs")
cor(year,uk,use = "complete.obs")
cor(year,ukraine,use = "complete.obs")
cor(year,uzbekistan,use = "complete.obs")
cor(year,world,use = "complete.obs")


lm(vietnam~year)
lm(usa~year)
lm(algeria~year)
lm(argentina~year)
lm(australia~year)
lm(austria~year)
lm(azerbaijan~year)
lm(belarus~year)
lm(belgium~year)
lm(brazil~year)
lm(canada~year)
lm(china~year)
lm(colombia~year)
lm(czech~year)
lm(ecuador~year)
lm(egypt~year)
lm(finland~year)
lm(france~year)
lm(germany~year)
lm(hungry~year)
lm(india~year)
lm(indonesia~year)
lm(iran~year)
lm(Italy~year)
lm(japan~year)
lm(kazakhstan~year)
lm(malaysia~year)
lm(mexico~year)
lm(moroco~year)
lm(netherlands~year)
lm(pak~year)
lm(phillipines~year)
lm(poland~year)
lm(portugal~year)
lm(romania~year)
lm(russia~year)
lm(serbia~year)
lm(slovenia~year)
lm(solvakia~year)
lm(southAfrica~year)
lm(southKorea~year)
lm(spain~year)
lm(sweden~year)
lm(taiwan~year)
lm(thailand~year)
lm(tunisia~year)
lm(turkey~year)
lm(uk~year)
lm(ukraine~year)
lm(uzbekistan~year)
lm(world~year)


library(moments)
skewness(vietnam,na.rm = TRUE)
skewness(usa,na.rm = TRUE)
skewness(algeria,na.rm=TRUE)
skewness(argentina,na.rm=TRUE)
skewness(australia,na.rm=TRUE)
skewness(austria,na.rm=TRUE)
skewness(azerbaijan,na.rm=TRUE)
skewness(belarus,na.rm=TRUE)
skewness(belgium,na.rm=TRUE)
skewness(brazil,na.rm=TRUE)
skewness(canada,na.rm=TRUE)
skewness(china,na.rm=TRUE)
skewness(colombia,na.rm=TRUE)
skewness(czech,na.rm=TRUE)
skewness(ecuador,na.rm=TRUE)
skewness(egypt,na.rm=TRUE)
skewness(finland,na.rm=TRUE)
skewness(france,na.rm=TRUE)
skewness(germany,na.rm=TRUE)
skewness(hungry,na.rm=TRUE)
skewness(india,na.rm=TRUE)
skewness(indonesia,na.rm=TRUE)
skewness(iran,na.rm=TRUE)
skewness(Italy,na.rm=TRUE)
skewness(japan,na.rm=TRUE)
skewness(kazakhstan,na.rm=TRUE)
skewness(malaysia,na.rm=TRUE)
skewness(mexico,na.rm=TRUE)
skewness(moroco,na.rm=TRUE)
skewness(netherlands,na.rm=TRUE)
skewness(pak,na.rm=TRUE)
skewness(phillipines,na.rm=TRUE)
skewness(poland,na.rm=TRUE)
skewness(portugal,na.rm=TRUE)
skewness(romania,na.rm=TRUE)
skewness(russia,na.rm=TRUE)
skewness(serbia,na.rm=TRUE)
skewness(slovenia,na.rm=TRUE)
skewness(solvakia,na.rm=TRUE)
skewness(southAfrica,na.rm=TRUE)
skewness(southKorea,na.rm=TRUE)
skewness(spain,na.rm=TRUE)
skewness(sweden,na.rm=TRUE)
skewness(taiwan,na.rm=TRUE)
skewness(thailand,na.rm=TRUE)
skewness(tunisia,na.rm=TRUE)
skewness(turkey,na.rm=TRUE)
skewness(uk,na.rm=TRUE)
skewness(ukraine,na.rm=TRUE)
skewness(uzbekistan,na.rm=TRUE)
skewness(world,na.rm=TRUE)